# Generated by Django 4.0.5 on 2022-06-03 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('rooms', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_names', models.CharField(max_length=50)),
                ('zip_codes', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
            ],
            options={
                'verbose_name': 'User Search',
            },
        ),
    ]
