# Generated by Django 4.0.5 on 2022-06-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0003_scrapy_user_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapy',
            old_name='user_names',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='usersearch',
            old_name='user_names',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='usersearch',
            name='zip_codes',
        ),
    ]
