# Generated by Django 4.0.5 on 2022-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0004_rename_user_names_scrapy_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapy',
            name='price',
            field=models.CharField(max_length=1000),
        ),
    ]
