# Generated by Django 4.0.5 on 2022-06-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0005_alter_scrapy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapy',
            name='beds',
            field=models.CharField(max_length=30),
        ),
    ]
