# Generated by Django 4.0.5 on 2022-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes', '0006_alter_scrapy_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapy',
            name='average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
